import { useCallback, useEffect, useRef, useState } from 'react';
import YouTubePlayer, { type PlayerControls } from './YouTubePlayer';
import { fixtures, VIDEO_ID, VIDEO_DURATION } from './replay/manifest';
import { stateAt, replayTimeForMatchSecond } from './replay/engine';
import { runReplayCommand } from './replay/commands';
import { quoteIdentity, runLiveCommand } from './live/core';
import type { CommandResult, LiveFeed, Quote, ReplayState, TapeEvent } from './types';

type Mode='TAPE'|'LIVE';
type Point={time:number;prices:(number|null)[]};
const blankLive:LiveFeed={snapshot:null,history:[],status:'unavailable',error:null,lastAttemptAt:null,nextRefreshAt:null};
const formatTime=(seconds:number)=>{const s=Math.max(0,Math.floor(seconds));return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;};
const videoTime=(s:number)=>{const t=Math.floor(s);return `${Math.floor(t/3600).toString().padStart(2,'0')}:${Math.floor(t%3600/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`;};
const phaseName=(s:string)=>s.replaceAll('_',' ');
function Sparkline({values,color='#f2aa50',preserveGaps=false}:{values:(number|null)[];color?:string;preserveGaps?:boolean}){const clean=values.filter((v):v is number=>v!==null);if(clean.length<2)return <div className="spark-empty">Awaiting next tick</div>;const min=Math.min(...clean),max=Math.max(...clean),range=Math.max(.02,max-min);const points=clean.map((v,i)=>`${i/(clean.length-1)*200},${39-(v-min)/range*32}`).join(' ');const segments:string[][]=[];if(preserveGaps){let segment:string[]=[];values.forEach((v,i)=>{if(v===null){if(segment.length)segments.push(segment);segment=[];}else segment.push(`${i/Math.max(1,values.length-1)*200},${39-(v-min)/range*32}`);});if(segment.length)segments.push(segment);}return <svg className="sparkline" viewBox="0 0 200 44" role="img" aria-label={preserveGaps?'Observed price movement; gaps mean the quote was unavailable':'Price movement'}><path d="M0 40H200" stroke="#25303a"/>{preserveGaps?segments.map((segment,i)=>segment.length>1?<polyline key={i} points={segment.join(' ')} fill="none" stroke={color} strokeWidth="1.7" vectorEffect="non-scaling-stroke"/>:<circle key={i} cx={Number(segment[0].split(',')[0])} cy={Number(segment[0].split(',')[1])} r="1.7" fill={color}/>):<polyline points={points} fill="none" stroke={color} strokeWidth="1.7" vectorEffect="non-scaling-stroke"/>}</svg>;}
function ageLabel(time:string|null){if(!time)return 'Freshness unverified';const age=Math.max(0,(Date.now()-Date.parse(time))/1000);if(!Number.isFinite(age))return 'Freshness unverified';return age>120?`STALE · ${Math.floor(age/60)}m old`:`Updated ${Math.floor(age)}s ago`;}
function timestampLabel(time:string|null){if(!time||!Number.isFinite(Date.parse(time)))return 'Not exposed';return new Date(time).toLocaleString('en-GB',{timeZone:'Europe/London',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'short'});}
function App(){
  const [mode,setMode]=useState<Mode>(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('mode')?.toLowerCase()==='live'?'LIVE':'TAPE'),modeRef=useRef<Mode>(mode);
  const [replay,setReplay]=useState(()=>stateAt(0)),replayRef=useRef(replay),[history,setHistory]=useState<Point[]>([{time:0,prices:replay.quotes.map(q=>q.price)}]);
  const [diffs,setDiffs]=useState<(number|null)[]>([null,null,null]),[tick,setTick]=useState(0),lastBucket=useRef(-1);
  const [playing,setPlaying]=useState(false),[manual,setManual]=useState(false),manualRef=useRef(false),[rate,setRate]=useState(1),[playerError,setPlayerError]=useState<string|null>(null);
  const player=useRef<PlayerControls>(null),[live,setLive]=useState<LiveFeed>(blankLive),[liveLoading,setLiveLoading]=useState(false),[now,setNow]=useState(Date.now()),refreshLive=useRef<(()=>Promise<void>)|null>(null),lastLiveAttempt=useRef(0);
  const [input,setInput]=useState(''),[result,setResult]=useState<CommandResult|null>(null),[evidence,setEvidence]=useState<TapeEvent|null>(null),commandInput=useRef<HTMLInputElement>(null);
  const [seekInput,setSeekInput]=useState(''),[showHelp,setShowHelp]=useState(false);
  const commitTime=useCallback((seconds:number,isSeek=false)=>{if(modeRef.current!=='TAPE')return;const next=stateAt(Math.max(0,Math.min(VIDEO_DURATION-.01,seconds))),previous=replayRef.current;const boundary=next.fixture.id!==previous.fixture.id;
    if(Math.abs(next.videoSecond-previous.videoSecond)<.02&&!isSeek&&!boundary)return;
    replayRef.current=next;setReplay(next);const bucket=Math.floor(next.videoSecond);
    if(isSeek||boundary){setHistory([{time:next.videoSecond,prices:next.quotes.map(q=>q.price)}]);setDiffs([null,null,null]);lastBucket.current=bucket;setResult(null);setEvidence(null);setTick(t=>t+1);return;}
    const eventChanged=next.score.some((value,i)=>value!==previous.score[i])||next.redCards.some((value,i)=>value!==previous.redCards[i])||next.phase!==previous.phase;
    if(bucket!==lastBucket.current||eventChanged){lastBucket.current=bucket;const changes=next.quotes.map((q,i)=>q.price===null||previous.quotes[i]?.price==null?null:Math.round((q.price-previous.quotes[i].price!)*100)/100);const changed=changes.some(d=>d!==null&&d!==0);
      if(changed){setDiffs(changes);setTick(t=>t+1);setHistory(points=>[...points.filter(p=>p.time>=next.videoSecond-600),{time:next.videoSecond,prices:next.quotes.map(q=>q.price)}].slice(-601));}
      else if(next.phase==='FULL_TIME'||next.phase==='PENALTIES')setDiffs([null,null,null]);
    }
  },[]);
  const onVideoTime=useCallback((time:number,seek:boolean)=>{if(!manualRef.current)commitTime(time,seek);},[commitTime]);
  const onPlaying=useCallback((value:boolean)=>{if(modeRef.current==='TAPE'&&!manualRef.current)setPlaying(value);},[]);
  const seek=useCallback((seconds:number)=>{commitTime(seconds,true);if(!manualRef.current)player.current?.seek(seconds);},[commitTime]);
  const switchMode=(next:Mode)=>{player.current?.pause();modeRef.current=next;setMode(next);setResult(null);setEvidence(null);setDiffs([null,null,null]);setPlaying(false);setLiveLoading(false);if(next==='TAPE'){const value=replayRef.current;setHistory([{time:value.videoSecond,prices:value.quotes.map(q=>q.price)}]);}else setHistory([]);};
  const switchManual=(value:boolean)=>{if(value)player.current?.pause();manualRef.current=value;setManual(value);setPlaying(false);if(!value)player.current?.seek(replayRef.current.videoSecond);};
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!manual||!playing||mode!=='TAPE')return;let previous=performance.now();const timer=setInterval(()=>{const current=performance.now();const position=replayRef.current.videoSecond+(current-previous)/1000*rate;commitTime(position);if(position>=VIDEO_DURATION-.01)setPlaying(false);previous=current;},250);return()=>clearInterval(timer);},[manual,playing,mode,rate,commitTime]);
  useEffect(()=>{if(mode!=='LIVE')return;let cancelled=false,inFlight=false;const controller=new AbortController();const load=async()=>{if(cancelled||inFlight||Date.now()-lastLiveAttempt.current<60000)return;inFlight=true;lastLiveAttempt.current=Date.now();setNow(Date.now());setLiveLoading(true);try{const response=await fetch(import.meta.env.VITE_LIVE_FEED_URL||'/api/match-feed',{signal:controller.signal});if(!response.ok)throw new Error(`Live backend returned ${response.status}`);const data:LiveFeed=await response.json();if(!cancelled&&modeRef.current==='LIVE')setLive(data);}catch(error){if(!cancelled&&modeRef.current==='LIVE')setLive(old=>({...old,status:old.snapshot?'stale':'unavailable',error:error instanceof Error?error.message:'Live retrieval failed'}));}finally{inFlight=false;if(!cancelled&&modeRef.current==='LIVE')setLiveLoading(false);}};refreshLive.current=load;void load();const timer=setInterval(load,60000);return()=>{cancelled=true;controller.abort();clearInterval(timer);refreshLive.current=null;if(inFlight)lastLiveAttempt.current=0;};},[mode]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();commandInput.current?.focus();}if(event.key==='Escape'){setEvidence(null);setShowHelp(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  function execute(command:string){const value=command.trim();if(!value)return;setInput('');if(mode==='TAPE'){const match=/^REWIND\s+(\d+(?:\.\d+)?)$/i.exec(value);if(match)seek(replayTimeForMatchSecond(replay.fixture,Number(match[1])*60));setResult(runReplayCommand(value,replayRef.current));}else setResult(runLiveCommand(value,live));}
  const tape=mode==='TAPE',snapshot=live.snapshot,home=tape?replay.fixture.home:snapshot?.home||'England',away=tape?replay.fixture.away:snapshot?.away||'Czechia';
  const score=tape?replay.score:snapshot?.score,clock=tape?formatTime(replay.matchSecond):snapshot?.minute!=null?`${snapshot.minute}′`:'--:--';
  const liveQuotes=[home,'Draw',away].map(name=>snapshot?.quotes.find(q=>q.outcome===name));
  const phase=tape?replay.phase:snapshot?.phase||'AWAITING SOURCE',quotes:Quote[]=tape?replay.quotes:[home,'Draw',away].map((name,i)=>({outcome:name,price:liveQuotes[i]?.price??null}));
  const latestEvents=tape?[...replay.events].reverse():[];const calibration=tape&&replay.verification!=='video_verified';
  const liveWindow=live.history.filter(s=>{const time=Date.parse(s.fetchedAt);return Number.isFinite(time)&&time>=now-600000&&time<=now;});
  if(snapshot&&Date.parse(snapshot.fetchedAt)>=now-600000&&Date.parse(snapshot.fetchedAt)<=now&&!liveWindow.some(s=>s.fetchedAt===snapshot.fetchedAt))liveWindow.push(snapshot);
  liveWindow.sort((a,b)=>Date.parse(a.fetchedAt)-Date.parse(b.fetchedAt));
  const marketHistory=tape?history:liveWindow.map(s=>({time:Date.parse(s.fetchedAt)/1000,prices:liveQuotes.map(current=>current?s.quotes.find(q=>quoteIdentity(q)===quoteIdentity(current))?.price??null:null)}));
  const lastLive=[...liveWindow].reverse().find(s=>s.id!==snapshot?.id);
  const quoteDiffs=tape?diffs:liveQuotes.map(current=>{const previous=current?lastLive?.quotes.find(q=>quoteIdentity(q)===quoteIdentity(current)):null;return current&&previous?Math.round((current.price-previous.price)*100)/100:null;});
  const liveResultSources=result?.evidenceIds.flatMap(id=>{const observation=[...(snapshot?[snapshot]:[]),...live.history].find(s=>s.id===id);return observation?observation.sources.map(source=>({...source,observationId:id,fetchedAt:observation.fetchedAt})):[];})??[];
  const currentPhase=tape?phaseName(replay.phase):phaseName(phase),refreshSeconds=Math.max(0,Math.ceil((lastLiveAttempt.current+60000-now)/1000));
  return <div className="terminal">
    <header className="topbar"><div className="brand"><span className="brand-mark">▰</span> TOUCHLINE<span className="brand-sub">FOOTBALL INTELLIGENCE</span></div><div className="topbar-right"><span className="system-status"><i/> SYSTEM ONLINE</span><span className="local-clock">{new Date(now).toLocaleTimeString('en-GB',{timeZone:'Europe/London'})} BST</span><button className="help-button" onClick={()=>setShowHelp(v=>!v)} aria-label="Show commands">?</button></div></header>
    <div className="contextbar"><div className="context-left"><span className="context-label">MATCH DESK</span><span>{tape?replay.fixture.competition:'UEFA NATIONS LEAGUE'} / {tape?replay.fixture.date:'06 OCT 2026'}</span></div><div className="mode-toggle" aria-label="Data mode"><button className={!tape?'active live-mode':''} onClick={()=>switchMode('LIVE')}>● LIVE</button><button className={tape?'active':''} onClick={()=>switchMode('TAPE')}>↺ TAPE</button></div></div>
    <section className="scoreboard"><div className="team home"><div className="team-symbol">{home.split(' ').map(x=>x[0]).join('').slice(0,3)}</div><div><span className="team-kicker">HOME</span><h1>{home}</h1></div></div><div className="score-centre"><div className="score">{score?`${score[0]} — ${score[1]}`:'— : —'}</div><div className="match-clock"><span className={playing?'pulse-dot':'idle-dot'}/>{clock}<span className="phase-label">{currentPhase}</span></div>{tape&&(replay.phase==='PENALTIES'||replay.shootoutResult)&&<div className="shootout-label">{replay.shootoutResult?`PENALTIES ${replay.shootoutResult.join(' — ')} · REGULATION DRAW`:'SHOOTOUT IN PROGRESS · KICK TIMINGS UNAVAILABLE'}</div>}</div><div className="team away"><div><span className="team-kicker">AWAY</span><h1>{away}</h1></div><div className="team-symbol away-symbol">{away.split(' ').map(x=>x[0]).join('').slice(0,3)}</div></div></section>
    <div className={`data-banner ${tape?'replay-banner':'live-banner'}`}><span>{tape?'↺ REPLAY · SIMULATED ODDS · RECORDED EVENTS':'● LIVE · PUBLIC SOURCE RETRIEVAL'}</span>{!tape&&<button type="button" onClick={()=>void refreshLive.current?.()} disabled={liveLoading||refreshSeconds>0} aria-label="Refresh live sources">REFRESH SOURCES {liveLoading?'…':refreshSeconds>0?`IN ${refreshSeconds}s`:'↻'}</button>}<span>{tape?(manual?'MANUAL CLOCK · VIDEO NOT SYNCHRONISED':calibration?'VIDEO TIMING ESTIMATED · CALIBRATION PENDING':'VERIFIED VIDEO TIMELINE'):liveLoading?'RETRIEVING SOURCES…':live.status.toUpperCase()}</span></div>
    <main className={`workspace ${tape?'tape-workspace':'live-workspace'}`}>
      <section className="panel video-panel"><div className="panel-heading"><h2>{tape?'MATCH REPLAY':'LIVE BROADCAST'}</h2><span className="panel-number">01 / VISION</span></div>
        {tape?<><div className="video-toolbar"><select aria-label="Replay match" value={replay.fixture.id} onChange={e=>{const f=fixtures.find(x=>x.id===e.target.value)!;seek(f.start);}}>{fixtures.map((f,i)=><option key={f.id} value={f.id}>{String(i+1).padStart(2,'0')} · {f.home} v {f.away}</option>)}</select><span className="yt-label">YOUTUBE / OFFICIAL PLAYER</span></div><YouTubePlayer ref={player} videoId={VIDEO_ID} initialTime={replay.videoSecond} active={!manual} onTime={onVideoTime} onPlaying={onPlaying} onError={setPlayerError}/>
        {playerError&&<div className="error-strip">{playerError} <a href={`https://www.youtube.com/watch?v=${VIDEO_ID}`} target="_blank" rel="noreferrer">Open YouTube ↗</a></div>}
        <div className="transport"><button className="play-control" aria-label={playing?'Pause replay':'Play replay'} onClick={()=>manual?setPlaying(!playing):playing?player.current?.pause():player.current?.play()}>{playing?'Ⅱ':'▶'}</button><button onClick={()=>seek(Math.max(replay.fixture.start,replay.videoSecond-30))} aria-label="Back 30 seconds">−30s</button><button onClick={()=>seek(Math.min(replay.fixture.end-.01,replay.videoSecond+30))} aria-label="Forward 30 seconds">+30s</button><span className="transport-time">{videoTime(replay.videoSecond)}</span><select aria-label="Playback speed" value={rate} onChange={e=>{setRate(Number(e.target.value));player.current?.rate(Number(e.target.value));}}>{[.5,1,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select><label className="manual-toggle"><input type="checkbox" checked={manual} onChange={e=>switchManual(e.target.checked)}/>Manual clock</label></div>
        <input className="timeline-slider" aria-label="Seek video" type="range" min={0} max={VIDEO_DURATION-1} step={1} value={Math.floor(replay.videoSecond)} onChange={e=>seek(Number(e.target.value))}/>
        <div className="jump-row"><span>JUMP TO MATCH MINUTE</span><form onSubmit={e=>{e.preventDefault();const n=Number(seekInput);if(Number.isFinite(n)&&n>=0){seek(replayTimeForMatchSecond(replay.fixture,n*60));setSeekInput('');}}}><input aria-label="Match minute" inputMode="decimal" placeholder="e.g. 65" value={seekInput} onChange={e=>setSeekInput(e.target.value)}/><button type="submit">GO ↗</button></form></div></>:<div className="live-video-fallback"><div className="broadcast-grid"/><span className="broadcast-icon">▷</span><h3>Official live broadcast</h3><p>Watch the match on ITVX. The terminal retrieves its intelligence independently.</p><a className="primary-link" href="https://www.itv.com/watch" target="_blank" rel="noreferrer">OPEN ITV LIVE ↗</a><span className="muted">Official player · no video redistribution</span></div>}
        <div className="video-caption"><span>{tape?'BUNDLED REPLAY · NO API REQUIRED':'ITV / ITVX'}</span><span>{tape?`${fixtures.findIndex(f=>f.id===replay.fixture.id)+1} OF ${fixtures.length} MATCHES`:'OFFICIAL PLAYER LINK'}</span></div>
      </section>
      <section className="panel market-panel"><div className="panel-heading"><h2>MARKET TAPE</h2><span className="panel-number">02 / PRICES</span></div><div className="market-meta"><span>1X2 · REGULATION RESULT</span><span className="badge">{tape?'SIMULATED':'SOURCED'}</span></div>
        {quotes.map((q,i)=>{const delta=quoteDiffs[i],direction=delta==null||delta===0?'flat':delta<0?'shortening':'drifting',source=liveQuotes[i];return <div className={`quote-row ${direction}`} key={`${mode}-${home}-${q.outcome}`}><div className="quote-label"><span className="outcome-index">{i===0?'1':i===1?'X':'2'}</span><span>{q.outcome}</span></div><div className="quote-prices"><strong key={`${tape?tick:snapshot?.id}-${i}`} className={delta?'price-flash':''}>{q.settled?q.settled:q.price?.toFixed(2)||'—'}</strong><span className={`price-change ${direction}`}>{delta==null?'—':delta===0?'→ 0.00':`${delta<0?'↓':'↑'} ${delta>0?'+':''}${delta.toFixed(2)}`}</span></div><Sparkline values={marketHistory.map(p=>p.prices[i]??null)} preserveGaps={!tape} color={direction==='shortening'?'#6cdeb6':direction==='drifting'?'#fa8a79':'#f2aa50'}/>{!tape&&<div className="source-line">{source?<><a href={source.sourceUrl} target="_blank" rel="noreferrer">{source.bookmaker} · {source.sourceName} ↗</a><span>{source.market} · ten-minute observed history</span><span>Source update: {timestampLabel(source.sourceUpdatedAt)} · {ageLabel(source.sourceUpdatedAt)}</span><span>Retrieved: {timestampLabel(source.fetchedAt)}{live.status==='stale'?' · STALE / latest retrieval failed':` · ${ageLabel(source.fetchedAt)}`}</span></>:<span>No verified source quote · freshness unverified</span>}</div>}</div>})}
        <div className="market-key"><span><i className="green-dot"/> SHORTENING</span><span><i className="red-dot"/> DRIFTING</span></div><div className="market-note">{tape?'Model prices respond to score, time and red cards. They are not historical bookmaker prices.':'Prices move only when source quotes change. Public retrieval is not a streaming market feed.'}</div>
        <div className="market-status"><span className="status-dot"/> {tape?(playing?'TAPE ADVANCING':'TAPE PAUSED'):`${liveLoading?'POLL IN PROGRESS':'60s REFRESH INTERVAL'}`}<span>{marketHistory.length} OBSERVATIONS</span></div>
      </section>
      <section className="panel feed-panel"><div className="panel-heading"><h2>EVENT WIRE</h2><span className="panel-number">03 / EVIDENCE</span></div><div className="feed-list">{tape?latestEvents.length?latestEvents.map(event=><button className="feed-event" key={event.id} onClick={()=>setEvidence(event)}><span className="event-time">{event.minute}{event.addedTime?`+${event.addedTime}`:''}′</span><div><span className={`event-kind ${event.type==='GOAL'?'goal':event.type==='RED_CARD'?'red':''}`}>{phaseName(event.type)}</span><p>{event.player} · {event.side==='home'?home:away}</p><span className="event-origin">RECORDED EVENT / {event.verification==='video_verified'?'VIDEO VERIFIED':'TIMING ESTIMATED'} ↗</span></div></button>):<div className="empty-feed"><span>WAITING FOR KICKOFF</span><p>Events appear as playback reaches them. Future incidents stay hidden.</p><button onClick={()=>{const next=replay.fixture.events.find(e=>e.videoSecond>replay.videoSecond);if(next)seek(Math.max(replay.fixture.start,next.videoSecond-8));}}>JUMP BEFORE FIRST EVENT ↗</button></div>:snapshot?.events.length?snapshot.events.slice().reverse().slice(0,20).map(event=><a className="feed-event" href={event.sourceUrl} key={event.id} target="_blank" rel="noreferrer"><span className="event-time">{event.minute==null?'—':`${event.minute}′`}</span><div><span className="event-kind">FACT</span><p>{event.description}</p><span className="event-origin">{event.sourceName} ↗</span></div></a>):<div className="empty-feed"><span>{liveLoading?'RETRIEVING LIVE EVIDENCE':'SOURCE NOT AVAILABLE'}</span><p>{live.error||'Live reports will appear when the backend returns sourced match observations.'}</p></div>}</div><div className="feed-footer"><span>PROVENANCE REQUIRED</span><span>{tape?latestEvents.length:snapshot?.events.length||0} EVENTS</span></div></section>
    </main>
    <section className="stats-strip"><span className="strip-label">MATCH STATE</span>{tape?<><div><span>SCORE</span><strong>{score?.join(' : ')}</strong></div><div><span>RED CARDS</span><strong>{replay.redCards.join(' : ')}</strong></div><div><span>POSSESSION</span><strong className="unavailable">UNAVAILABLE</strong></div><div><span>SHOTS / xG</span><strong className="unavailable">UNAVAILABLE</strong></div></>:snapshot?.stats.length?snapshot.stats.map(stat=><a key={stat.name} href={stat.sourceUrl} target="_blank" rel="noreferrer"><span>{stat.name.toUpperCase()}</span><strong>{stat.home??'—'}{stat.unit} : {stat.away??'—'}{stat.unit}</strong></a>):<div className="stats-empty">Sourced statistics will appear here. Missing values stay unavailable.</div>}</section>
    <section className="analysis-grid"><div className="panel thesis-panel"><div className="panel-heading"><h2>INTELLIGENCE DESK</h2><span className="panel-number">04 / ANALYSIS</span></div><div className="thesis-content"><span className="epistemic">{tape?'MODEL · SIMULATED MARKET':'PUBLIC SOURCES · VERIFIED OBSERVATIONS'}</span><h3>{tape?replay.phase==='FULL_TIME'||replay.phase==='PENALTIES'?'Regulation market settled.':replay.score[0]===replay.score[1]?'The clock is changing the price of a draw.':`${replay.score[0]>replay.score[1]?home:away} lead. The market reprices the remaining time.`:'What has changed since the last observation?'}</h3><p>{tape?'Recorded goals and dismissals change the model. Price fluctuations are simulated; tactical claims need additional evidence.':live.error||'Public match reports supply sourced scores, events and statistics. NOW shows the latest facts; DELTA compares observations.'}</p><div className="quick-actions">{(tape?['NOW','DELTA 10','THESIS','DISPROVE','WATCH']:['NOW','DELTA']).map(command=><button key={command} onClick={()=>execute(command)}>{command}<span>↗</span></button>)}</div></div></div>
      <div className="panel command-panel"><div className="panel-heading"><h2>COMMAND RESPONSE</h2><span className="panel-number">05 / QUERY</span></div><div className="command-output" aria-live="polite">{result?<><div className="result-heading"><span>› {result.title}</span><span className="result-label">{tape?'REPLAY CONTEXT':'LIVE CONTEXT'}</span></div>{result.lines.map((line,i)=><p key={i}>{line}</p>)}{result.evidenceIds.length>0&&<div className="result-evidence">{tape?result.evidenceIds.map(id=>{const event=replay.events.find(e=>e.id===id);return event?<button key={id} onClick={()=>setEvidence(event)}>{event.minute}′ · {event.player} ↗</button>:null;}):liveResultSources.map(source=><a key={`${source.observationId}-${source.id}`} href={source.url} target="_blank" rel="noreferrer" title={`Observation retrieved ${timestampLabel(source.fetchedAt)}`}>{source.name} · {timestampLabel(source.fetchedAt)} ↗</a>)}</div>}</>:<><span className="standby-label">READY FOR YOUR QUERY</span><p className="command-example">› {tape?'DELTA 10':'NOW'}<span className="cursor">_</span></p><p>{tape?'What changed in the last ten match minutes?':'Show the latest verified match observations.'}</p><span className="muted">{tape?'Seek anywhere. The replay rebuilds its understanding.':'NOW shows sourced facts. DELTA compares verified observations.'}</span></>}</div></div></section>
    <form className="command-bar" onSubmit={e=>{e.preventDefault();execute(input);}}><span className="command-prompt">›</span><input ref={commandInput} aria-label="Terminal command" value={input} onChange={e=>setInput(e.target.value)} placeholder={tape?'NOW  /  DELTA 10  /  DISPROVE  /  PLAYER <name>  /  REWIND <minute>':'NOW  /  DELTA'} autoComplete="off" spellCheck={false}/><span className="shortcut">⌘ K</span><button type="submit">EXECUTE ↵</button></form>
    <footer className="bottom-bar"><span><i className="green-dot"/> {tape?'LOCAL REPLAY ENGINE':'PUBLIC MATCH SOURCES'} <span className="footer-divider">/</span> {tape?manual?'MANUAL CLOCK':'YOUTUBE CLOCK · 250ms':'WEB RETRIEVAL · 60s'}</span><span>OBSERVATIONS ≠ INFERENCES <span className="footer-divider">/</span> TOUCHLINE 1.0</span></footer>
    {evidence&&<div className="drawer-backdrop" onClick={()=>setEvidence(null)}><aside className="evidence-drawer" onClick={e=>e.stopPropagation()}><div className="panel-heading"><h2>EVENT PROVENANCE</h2><button onClick={()=>setEvidence(null)} aria-label="Close evidence">✕</button></div><span className="epistemic">RECORDED EVENT</span><h3>{evidence.player}</h3><p>{phaseName(evidence.type)} · {evidence.minute}{evidence.addedTime?`+${evidence.addedTime}`:''}′</p><dl><dt>Team</dt><dd>{evidence.side==='home'?home:away}</dd><dt>Video position</dt><dd>{videoTime(evidence.videoSecond)}</dd><dt>Timing verification</dt><dd>{evidence.verification==='video_verified'?'Checked in official player':'Estimated from match report; video calibration pending'}</dd><dt>Observation</dt><dd>{evidence.note||'Match report supports the event.'}</dd></dl><a href={evidence.sourceUrl} target="_blank" rel="noreferrer">OPEN SOURCE REPORT ↗</a><button className="primary-link" onClick={()=>{seek(evidence.videoSecond);setEvidence(null);}}>SEEK TO EVENT ▶</button></aside></div>}
    {showHelp&&<div className="drawer-backdrop" onClick={()=>setShowHelp(false)}><div className="help-dialog" onClick={e=>e.stopPropagation()}><div className="panel-heading"><h2>COMMAND DIRECTORY</h2><button onClick={()=>setShowHelp(false)} aria-label="Close commands">✕</button></div>{(tape?[['NOW','State of the match'],['DELTA 10','Material changes over ten match minutes'],['THESIS','Strongest supported interpretation'],['DISPROVE','Challenge that interpretation'],['PLAYER <name>','Recorded involvement'],['WHY','Explain the evidence'],['REWIND <minute>','Seek and reconstruct'],['WATCH','Signals worth watching next']]:[['NOW','Latest sourced match observations'],['DELTA','Price changes between verified observations']]).map(([cmd,text])=><div className="help-row" key={cmd}><code>{cmd}</code><span>{text}</span></div>)}<p>⌘/Ctrl K focuses the command line. Escape closes this panel.</p></div></div>}
  </div>;
}
export default App;
